### ISSUE TITLE
您好，我用您的代码跑出来的结果比全卸载性能都差很多，是我运行的问题吗?

### ISSUE THREAD

**Issue by xizhulove** [nju-cn/MEC_offloading#4]

**Comment by sling0318** [comment]
看了代码，我觉得是传输模型那里写错了，我按照论文的模型重写了一遍，性能就正确了

**Comment by xizhulove** [comment]
@sling0318 您好，那您方便把您改的代码分享给我一下吗？我想学习一下，感谢

**Comment by sling0318** [comment]
discount = 0.01    

    local_time = lam_local * workload * cycle_perbyte * (1 - percen)/(local_comp) + wait_local * cycle_perbyte

    local_energy = beta_local * workload * (1 - percen)

    local_only = lam_local * workload * cycle_perbyte/(local_comp) + wait_local * cycle_perbyte + beta_local * workload


    remote_time = lam_re * workload * cycle_perbyte * percen / (servers_cap[target_server]) + wait_server * cycle_perbyte + \
                    workload * percen / (uplink[target_server]) + discount * workload / (downlink[target_server])

    remote_energy = beta_re * workload * percen

    time_cost = local_time + remote_time

    energy_cost = local_energy + remote_energy

    remote_only = lam_re * workload * cycle_perbyte / (servers_cap[target_server]) + wait_server * cycle_perbyte + \
                    workload / (uplink[target_server]) + discount * workload / (downlink[target_server]) + \
                    beta_re * workload

    total_cost = 0.6 * time_cost + 0.4 * energy_cost

**Comment by xizhulove** [comment]
@sling0318 感谢您

**Comment by xizhulove** [comment]
> ```
> discount = 0.01    
> 
> local_time = lam_local * workload * cycle_perbyte * (1 - percen)/(local_comp) + wait_local * cycle_perbyte
> 
> local_energy = beta_local * workload * (1 - percen)
> 
> local_only = lam_local * workload * cycle_perbyte/(local_comp) + wait_local * cycle_perbyte + beta_local * workload
> 
> 
> remote_time = lam_re * workload * cycle_perbyte * percen / (servers_cap[target_server]) + wait_server * cycle_perbyte + \
>                 workload * percen / (uplink[target_server]) + discount * workload / (downlink[target_server])
> 
> remote_energy = beta_re * workload * percen
> 
> time_cost = local_time + remote_time
> 
> energy_cost = local_energy + remote_energy
> 
> remote_only = lam_re * workload * cycle_perbyte / (servers_cap[target_server]) + wait_server * cycle_perbyte + \
>                 workload / (uplink[target_server]) + discount * workload / (downlink[target_server]) + \
>                 beta_re * workload
> 
> total_cost = 0.6 * time_cost + 0.4 * energy_cost
> ```



> ```
> discount = 0.01    
> 
> local_time = lam_local * workload * cycle_perbyte * (1 - percen)/(local_comp) + wait_local * cycle_perbyte
> 
> local_energy = beta_local * workload * (1 - percen)
> 
> local_only = lam_local * workload * cycle_perbyte/(local_comp) + wait_local * cycle_perbyte + beta_local * workload
> 
> 
> remote_time = lam_re * workload * cycle_perbyte * percen / (servers_cap[target_server]) + wait_server * cycle_perbyte + \
>                 workload * percen / (uplink[target_server]) + discount * workload / (downlink[target_server])
> 
> remote_energy = beta_re * workload * percen
> 
> time_cost = local_time + remote_time
> 
> energy_cost = local_energy + remote_energy
> 
> remote_only = lam_re * workload * cycle_perbyte / (servers_cap[target_server]) + wait_server * cycle_perbyte + \
>                 workload / (uplink[target_server]) + discount * workload / (downlink[target_server]) + \
>                 beta_re * workload
> 
> total_cost = 0.6 * time_cost + 0.4 * energy_cost
> ```

**Comment by nju-cn** [comment]
邮件已收到

**Comment by charfole** [comment]
@xizhulove @sling0318 你们好，我最近也在学习这篇论文，我用 python3.6 和 tf1.5 运行会有报错，请问你们成功运行的环境是怎样的呢？

**Comment by nju-cn** [comment]
邮件已收到
